site_name: Coding Guidelines

theme:
    name: material
    favicon: img/favicon.ico
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top

copyright: This work © 2021 by Darius Weber under <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank" rel="noopener noreferrer">GNU GPLv3</a>
repo_url: https://github.com/ManticSic/coding-guidelines
repo_name: GitHub
edit_uri: edit/main/coding-guidelines/docs/

nav:
    - Einleitung: index.md
    - Guidelines:
            - General:
                    - Version Control: guidelines/general/11000.md
                    - Updates Policy: guidelines/general/12000.md
                    - Tools und Automatismen: guidelines/general/13000.md
                    - Namenskonvention: guidelines/general/14000.md
                    - Maintainability: guidelines/general/15000.md
                    - Dokumentation: guidelines/general/16000.md

plugins:
    - search: {}
