site_name: Coding Guidelines

theme:
  name: material
  favicon: img/favicon.ico
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top

copyright: This work © 2021 by Darius Weber under <a href="https://www.gnu.org/licenses/gpl-3.0.en.html" target="_blank" rel="noopener noreferrer">GNU GPLv3</a>
repo_url: https://github.com/ManticSic/coding-guidelines
repo_name: GitHub
edit_uri: edit/main/coding-guidelines/docs/

nav:
  - Introduction: index.md
  - Guidelines:
      - General:
          - Version Control: guidelines/general/11000.md
          - Update Policy: guidelines/general/12000.md
          - Tools and Automation: guidelines/general/13000.md
          - Namming Conventions: guidelines/general/14000.md
          - Maintainability: guidelines/general/15000.md
          - Documentation: guidelines/general/16000.md
          - Exceptions and Process Termination: guidelines/general/18000.md

plugins:
  - search: { }
  - git-revision-date: { }
  - i18n:
      default_language: en
      languages:
        en: English
        de: Deutsch
      nav_translations:
        de:
          Introduction: Einleitung
          Tools and Automation: Tools und Automatisierung
          Namming Conventions: Namenskonvention
          Documentation: Dokumentation
          Exceptions and Process Termination: Exceptions und Prozessbeendigung
